name: 'Run Doctrine Migrations'
description: 'A Github action that exposes the doctrine-migrations executable '
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  command:
    description: 'The doctrine-migrations command you want to run'
    required: true
    default: 'migrations:status'
